nginx:
  image: nginx
  volumes:
    - /usr/share/nginx/html
    - ./opt/certs:/etc/nginx/certs:ro
    - ./vhost.d:/etc/nginx/vhost.d
    - ./conf.d:/etc/nginx/conf.d
    - ./htpasswd:/etc/nginx/htpasswd
  ports:
    - "80:80"
    - "443:443"
  restart: always

gen:
  image: jwilder/docker-gen
  command: -notify-sighup proxy_nginx_1 -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
  volumes_from:
    - nginx
  restart: always

le:
  image: jrcs/letsencrypt-nginx-proxy-companion
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - ./opt/certs:/etc/nginx/certs:rw
    - ./vhost.d:/etc/nginx/vhost.d
  volumes_from:
    - nginx
  environment:
    - NGINX_DOCKER_GEN_CONTAINER=proxy_gen_1
  restart: always
